---
- name: define ocp_project
  set_fact:
    ocp_project: "fsi-cc-dispute-{{guid}}"

    # Templates come from here: https://raw.githubusercontent.com/jorgemoralespou/ose-sample-apps-layouts

- name: Create project for FSI Credit Card Dispute demo
  shell: |
         oc new-project {{ocp_project}} \
         --display-name="FSI Credit Card Dispute Demo" \
         --description="FSI Credit Card Dispute Demo"
  ignore_errors: true

- name: "Label namespace"
  command: "oc label namespace {{ocp_project}} AAD='{{guid}}'"

#- name: Set project limit LimitRange
#  shell: "oc create -f /tmp/{{guid}}//limit-range.yaml -n {{ocp_project}}"


- name: Import ImageStreams PAM
  shell: "oc create -f {{pam_imagestreams_yml}} -n {{ocp_project}}"

- name: Import ImageStreams Entando EAP 7.1
  shell: "oc create -f https://raw.githubusercontent.com/entando/entando-ops/master/Openshift/image-streams/entando-eap71-quickstart-openshift.json -n {{ocp_project}}"

- name: Import ImageStreams Entando Appbuilder
  shell: "oc create -f https://raw.githubusercontent.com/entando/entando-ops/master/Openshift/image-streams/appbuilder.json -n {{ocp_project}}"

- name: Import PAM Authoring template
  shell: "oc create -f {{pam_template_yml}} -n {{ocp_project}}"

- name: Import Entando EAP 7 template
  shell: "oc create -f https://raw.githubusercontent.com/entando/entando-ops/master/Openshift/templates/entando-eap71-quickstart.yml -n {{ocp_project}}"

- name: Create Secrets Business Central
  shell: oc process -f {{pam_secrets_template_yml}} -p SECRET_NAME=businesscentral-app-secret | oc create -f - -n {{ocp_project}}

- name: Create Secrets KIE-server
  shell: oc process -f {{pam_secrets_template_yml}} -p SECRET_NAME=kieserver-app-secret | oc create -f - -n {{ocp_project}}

- name: Create Service Account Business Central
  shell: oc create serviceaccount businesscentral-service-account -n {{ocp_project}}

- name: Create Service Account KIE Server
  shell: oc create serviceaccount kieserver-service-account -n {{ocp_project}}

- name: Link secrets and service account Business Central
  shell: oc secrets link --for=mount businesscentral-service-account businesscentral-app-secret -n {{ocp_project}}

- name: Link secrets and service account KIE-server
  shell: oc secrets link --for=mount kieserver-service-account kieserver-app-secret -n {{ocp_project}}

- name: Create ConfigMap Business Central
  shell: oc create configmap rhpam-bc-setup-config-map --from-file=/tmp/{{guid}}/bc-clone-git-repository.sh,/tmp/{{guid}}/provision-properties-static.sh -n {{ocp_project}}

#- name: Create PAM7 Authoring environment
#  shell: |
#         oc new-app --template=rhpam70-authoring \
#            -p APPLICATION_NAME="rhpam7-oih" \
#            -p KIE_ADMIN_USER="adminUser" \
#            -p KIE_ADMIN_PWD="test1234!" \
#            -p KIE_SERVER_CONTROLLER_USER="controllerUser" \
#            -p KIE_SERVER_CONTROLLER_PWD="test1234!" \
#            -p KIE_SERVER_USER="executionUser" \
#            -p KIE_SERVER_PWD="test1234!" \
#            -p BUSINESS_CENTRAL_HTTPS_SECRET="businesscentral-app-secret" \
#            -p KIE_SERVER_HTTPS_SECRET="kieserver-app-secret" \
#            -p MAVEN_REPO_URL="http://nexus:8081/content/groups/public/" \
#            -p MAVEN_REPO_USERNAME="deployment" \
#            -p MAVEN_REPO_PASSWORD="deployment123" \
#            -p BUSINESS_CENTRAL_MAVEN_USERNAME="mavenUser" \
#            -p BUSINESS_CENTRAL_MAVEN_PASSWORD="test1234!" \
#            -p BUSINESS_CENTRAL_MEMORY_LIMIT="2Gi" \
#            -p IMAGE_STREAM_NAMESPACE={{ocp_project}} -n {{ocp_project}}

- name: Create PAM7 Authoring environment 2
  shell: |
         oc new-app --template=rhpam70-authoring \
           --name={{pam_app_name}} \
           -p APPLICATION_NAME={{pam_app_name}} \
           -p BUSINESS_CENTRAL_HTTPS_SECRET=businesscentral-app-secret \
           -p KIE_SERVER_HTTPS_SECRET=kieserver-app-secret \
           -p KIE_SERVER_ID=kie-server \
           -p IMAGE_STREAM_NAMESPACE={{ocp_project}} \
           -p IMAGE_STREAM_TAG=1.1 \
           -p KIE_ADMIN_USER=kieAdmin \
           -p KIE_ADMIN_PWD="kieAdmin!23" \
           -p KIE_SERVER_USER=kieUser \
           -p KIE_SERVER_PWD="kieUser!23" \
           -p BUSINESS_CENTRAL_VOLUME_CAPACITY="1Gi" \
           -p BUSINESS_CENTRAL_MEMORY_LIMIT="2Gi" \
           -p EXCECUTION_SERVER_MEMORY_LIMIT="2Gi" \
           -p DB_VOLUME_CAPACITY="4Gi"

#-p BUSINESS_CENTRAL_HTTPS_KEYSTORE=businesscentral.jks \
#-p BUSINESS_CENTRAL_HTTPS_NAME=businesscentral \
#-p BUSINESS_CENTRAL_HTTPS_PASSWORD=$BC_STORE_PWD \
#-p KIE_SERVER_HTTPS_KEYSTORE=kieserver.jks \
#-p KIE_SERVER_HTTPS_NAME=kieserver \
#-p KIE_SERVER_HTTPS_PASSWORD=$KS_STORE_PWD \
#-p BUSINESS_CENTRAL_HOSTNAME_HTTP="$PROJ-businesscentral.$OCP_DOMAIN_SUFFIX" \
#-p BUSINESS_CENTRAL_HOSTNAME_HTTPS="secure-$PROJ-businesscentral.$OCP_DOMAIN_SUFFIX" \
#-p EXECUTION_SERVER_HOSTNAME_HTTP="$PROJ-kieserver.$OCP_DOMAIN_SUFFIX" \
#-p EXECUTION_SERVER_HOSTNAME_HTTPS="secure-$PROJ-kieserver.$OCP_DOMAIN_SUFFIX" \

#- name: "Add ConfigMap as Volume to Business Central DC"
#  shell: oc volume dc/{{pam_app_name}}-rhpamcentr --add --name=config-volume --configmap-name=rhpam-bc-setup-config-map --mount-path=/tmp/config-files

#- name: "Add BC deployment hook."
#  shell: oc set deployment-hook dc/{{pam_app_name}}-rhpamcentr --post -c {{pam_app_name}}-rhpamcentr -e BC_URL="http://rhpam7-oih-rhpamcentr:8080" -v config-volume --failure-policy=abort -- /bin/bash /tmp/config-files/bc-clone-git-repository.sh

- name: "Get KIE-Server Route"
  shell: "oc get route {{pam_app_name}}-kieserver | awk 'FNR > 1 {print $2}'"
  register: oc_get_route_output

- name: "Set KIE Server Route fact"
  set_fact:
    kie_server_route: "{{ oc_get_route_output.stdout }}"

- name: "Get OCP Domain Suffix"
  shell: "oc get route pam-kieserver | awk 'FNR > 1 {print $2}'| cut -d\".\" -f2-"
  register: oc_get_domain_suffix_output

- name: "OCP Domain Suffix fact"
  set_fact:
    ocp_domain_suffix: "{{ oc_get_domain_suffix_output.stdout }}"

# Entando deployment
- name: "Create Entando Customer Application"
  shell: |
         oc new-app --template={{ocp_project}}/entando-eap-quickstart \
           -p APPLICATION_NAME="{{entando_app_name_customer}}" \
           -p ENTANDO_RUNTIME_HOSTNAME_HTTP="{{entando_app_name_customer}}.{{ocp_domain_suffix}}" \
           -p KIE_SERVER_BASE_URL="http://{{kie_server_route}}" \
           -p KIE_SERVER_USERNAME=kieUser \
           -p KIE_SERVER_PASSWORD="kieUser!23" \
           -p SOURCE_REPOSITORY_URL={{entando_customer_repo}} \
           -p SOURCE_REPOSITORY_REF={{entando_branch}} \
           -p ENTANDO_WEB_CONTEXT=fsi-credit-card-dispute-customer \
           -p IMAGE_STREAM_NAMESPACE={{ocp_project}} \
           -p IMAGE_STREAM_TAG=latest

- name: "Create Entando Admin Application"
  shell: |
         oc new-app --template={{ocp_project}}/entando-eap-quickstart \
           -p APPLICATION_NAME="{{entando_app_name_admin}}" \
           -p ENTANDO_RUNTIME_HOSTNAME_HTTP="{{entando_app_name_admin}}.{{ocp_domain_suffix}}" \
           -p KIE_SERVER_BASE_URL="http://{{kie_server_route}}" \
           -p KIE_SERVER_USERNAME=kieUser \
           -p KIE_SERVER_PASSWORD="kieUser!23" \
           -p SOURCE_REPOSITORY_URL={{entando_admin_repo}} \
           -p SOURCE_REPOSITORY_REF={{entando_branch}} \
           -p ENTANDO_WEB_CONTEXT=fsi-credit-card-dispute-admin \
           -p IMAGE_STREAM_NAMESPACE={{ocp_project}} \
           -p IMAGE_STREAM_TAG=latest

#### Wait for the build to complete before slapping on the quota ....
- include_tasks: ./wait_for_build.yml
  static: no
  vars:
    build_to_wait:
      - "{{entando_app_name_customer}}-s2i-dbrebuild"
      - "{{entando_app_name_admin}}-s2i-dbrebuild"

#### Wait for the deployment to complete before slapping on the quota ...
- include_tasks: ./wait_for_deploy.yml
  static: no
  vars:
    pod_to_wait:
      - "{{entando_app_name_customer}}-runtime"
      - "{{entando_app_name_admin}}-runtime"
      - "{{pam_app_name}}-rhpamcentr"
      - "{{pam_app_name}}-kieserver"

#- name: "Start build of BPM Process application"
#  shell: "oc start-build co"

- name: Annotate the completed project as requested by user
  shell: "oc annotate namespace {{ocp_project}} openshift.io/requester={{ocp_username}} --overwrite"

- name: Give user access to the completed project
  shell: "oc policy add-role-to-user admin {{ocp_username}} -n {{ocp_project}}"

- name: workload Tasks Complete
  debug:
    msg: workload Tasks Complete
