apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "core-resource-limits"
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "1"
        memory: "2Gi"
      min:
        cpu: "100m"
        memory: "128Mi"
    - type: "Container"
      max:
        cpu: "1"
        memory: "2Gi"
      min:
        cpu: "100m"
        memory: "128Mi"
      default:
        cpu: "1"
        memory: "2Gi"
      defaultRequest:
        cpu: "500m"
        memory: "1Gi"
      maxLimitRequestRatio:
        cpu: "10"
